Add const validation
IB-ULFRI/homework-actions pull request #1
Opened 2023-10-27 09:42 UTC by JanezSedeljsak

I've introduced constant validation, allowing you to dynamically include constant variables in the workflow file. For instance, if you wish to include constants `[x, y, test_var, comment]`, you can do so by adding the following configuration:
```yml
- name: Check Syntax
  uses: JanezSedeljsak/homework-actions@main
  with:
    args: 'x y test_var comment'
```

In case you have a notebook file like this:
![image](https://github.com/IB-ULFRI/homework-actions/assets/43420276/a9946f10-3602-4d73-93e0-e9c918237e49)
As you can see from the notebook we only look at the most bottom decleration. The pipeline will now trigger an error message: 'ValueError: Invalid constant: 'comment'!'."

<b>Maybe you could add a new branch like `constant-check` so that this action can be separate from the old one.</b>

2023-11-14 09:33 UTC, MartinSpendl commented
First, thank you very much for making a pull request.
Using args to set variable names is fine and fits nicely with our agenda to keep GH actions simple and universal.
I would perhaps like to keep these two commands together so that the runtime of actions is low. There is a monthly time limit per organization.

There is just one caveat. While testing your solution, I noticed that, for example:
`bacteria_threshold = -1`
gets treated as an expression, thus throwing an error. 

Consider adding this condition to your `const_stuctured_check` function:

```
if isinstance(astnode, ast.UnaryOp) and isinstance(astnode.op, ast.USub):
        return isinstance(astnode.operand, (ast.Constant, ast.Num)) and isinstance(astnode.operand.n, int)
```

Please add, test, and ping me to check and merge PR before the 4th HW.

Thank you!

2023-11-14 10:25 UTC, MartinSpendl requested changes
Please add the handling of negative numbers to the const_structured_check function as described in the comment.

2023-11-14 21:28 UTC, JanezSedeljsak commented
@MartinSpendl I've added the change you suggested :)

2023-11-15 08:26 UTC, MartinSpendl commented
Thank you, @JanezSedeljsak!
Now, it works as intended. I will merge this now to use it for the next homework.

2023-11-15 08:26 UTC, merged